name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Updating data on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          script: |
            cd /driver_diary_back
            git reset --hard HEAD
            git pull 
            docker rm -f driver_app
            docker build -t driver_diary_build .
            docker network disconnect spring-net mysqldb
            docker network connect spring-net mysqldb
            docker run -d -p 8080:8080 --name driver_app --net spring-net -e MYSQL_HOST=mysqldb -e MYSQL_USER=${{ secrets.DEPLOY_MYSQL_USERNAME }} -e MYSQL_PASSWORD=${{ secrets.DEPLOY_MYSQL_PASSWORD }} driver_diary_build
            
