name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Working with remote server
    runs-on: ubuntu-latest
    steps:
      - name: Pulling
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          script: |
            cd /home/server/driver_diary_back
            git reset --hard HEAD
            git pull
            cd /home/server
            docker-compose stop driverdiary
            docker-compose build driverdiary
            docker-compose start driverdiary